server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KSaraiva/spring-cloud-challenge-config-repo.git
          search-paths: eats
          default-label: main